In [6]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"]="3"

%run cnn_model
from matplotlib import pyplot as plt
import tensorflow as tf




sess = tf.Session()
export_dir = "my_net/save_net.ckpt"
tf.reset_default_graph()

load_model=mnist_cnn_model()



with tf.Session() as sess:
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    ######saver = tf.train.import_meta_graph(args.netFile, clear_devices=True)
    saver.restore(sess, export_dir)
    #saver = tf.train.import_meta_graph(export_dir)
    #saver.restore(sess, tf.train.latest_checkpoint('my_net/'))
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    
    sess.run(tf.global_variables_initializer())
    all_vars = tf.trainable_variables()
    print("---------------------------------------------------")
    for v in all_vars:
        print("{}, value:\n{}".format(v.name, sess.run(v)))

        
'''
    load_model=mnist_cnn_model()
    load_model.set_value(all_vars[0], all_vars[1], all_vars[2], all_vars[4], all_vars[3], all_vars[5],
                         all_vars[6], all_vars[8], all_vars[7], all_vars[9])
    
    load_model.details()
    y = load_model.run_cnn()
    correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(load_model.label_placeholder, 1))
    print(sess.run(tf.argmax(y, 1)))
    
    
    tmp = load_model.img_placeholder
    plt.imshow(tmp)
    plt.show()
    '''
    
    

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO:tensorflow:Restoring parameters from my_net/save_net.ckpt


TypeError: Cannot interpret feed_dict key as Tensor: The name 'save/Const:0' refers to a Tensor which does not exist. The operation, 'save/Const', does not exist in the graph.

In [12]:
from cnn_model import mnist_cnn_model
import tensorflow as tf
from tensorflow.python.saved_model import (signature_constants, signature_def_utils, tag_constants, utils)

##############################################
#read model
export_dir = 'my_net/save_net.ckpt'
sess=tf.Session()
graph = tf.get_default_graph()




saver = tf.train.Saver()
saver.restore(sess, export_dir)
print(y_predict)
result = sess.run(y, feed_dict={x: data})


'''

#First let's load meta graph and restore weights
saver = tf.train.import_meta_graph(export_dir)
#saver.restore(sess, export_dir)

tf.saved_model.loader.load(sess, [tag_constants.TRAINING], export_dir)
print("restore success.")


v1  = graph.get_tensor_by_name('img_placeholder:0')
v2  = graph.get_tensor_by_name('label_placeholder:0')
v3  = graph.get_tensor_by_name('W_conv1:0')
v4  = graph.get_tensor_by_name('W_conv2:0')
v5  = graph.get_tensor_by_name('b_conv1:0')
v6  = graph.get_tensor_by_name('b_conv2:0')
v7  = graph.get_tensor_by_name('W_fc1:0')
v8  = graph.get_tensor_by_name('W_fc2:0')
v9  = graph.get_tensor_by_name('b_fc1:0')
v10 = graph.get_tensor_by_name('b_fc2:0')
prediction = restored_graph.get_tensor_by_name('prediction:0')


load_model=mnist_cnn_model()
load_model.set_value(v1, v2, v3, v5, v4, v6, v7, v9, v8, v10)
    
load_model.details()
y = load_model.run_cnn()
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(load_model.label_placeholder, 1))
print(y)

print(v1, v2, v10, prediction)
    
'''

ERROR! Session/line number was not unique in database. History logging moved to new session 267
INFO:tensorflow:Restoring parameters from my_net/save_net.ckpt


InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [32] rhs shape= [10]
	 [[{{node save_1/Assign_1}} = Assign[T=DT_FLOAT, _class=["loc:@Variable_1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable_1, save_1/RestoreV2:1)]]

Caused by op 'save_1/Assign_1', defined at:
  File "C:\Users\deoxys\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\deoxys\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\deoxys\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\Users\deoxys\Anaconda3\lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "C:\Users\deoxys\Anaconda3\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-610943b3191a>", line 14, in <module>
    saver = tf.train.Saver()
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1094, in __init__
    self.build()
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1106, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1143, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 787, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 428, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 119, in restore
    self.op.get_shape().is_fully_defined())
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tensorflow\python\ops\state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "C:\Users\deoxys\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [32] rhs shape= [10]
	 [[{{node save_1/Assign_1}} = Assign[T=DT_FLOAT, _class=["loc:@Variable_1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable_1, save_1/RestoreV2:1)]]


In [6]:
# import the inspect_checkpoint library
from tensorflow.python.tools import inspect_checkpoint as chkp

# print all tensors in checkpoint file
chkp.print_tensors_in_checkpoint_file("my_net/save_net.ckpt", tensor_name='', all_tensors=True)

tensor_name:  Variable
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
tensor_name:  Variable_1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
tensor_name:  Variable_10
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
tensor_name:  Variable_11
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
tensor_name:  Variable_12
[[[[ 9.76336598e-02  7.71846250e-03  5.47392443e-02 -3.25608812e-02
     4.66100127e-02 -9.34336409e-02  1.53990775e-01 -1.30210623e-01
    -8.50726664e-02  3.84880602e-02 -7.06779510e-02 -5.92379086e-02
    -5.84566919e-03 -1.16497893e-02 -7.42706731e-02  1.01803914e-01
     1.56169459e-01 -1.51200101e-01  6.47276267e-02 -1.00030117e-01
     2.66750548e-02 -9.71110091e-02  1.41191125e-01 -7.47229978e-02
    -6.98968396e-03  1.62775725e-01  1.09461211e-01  1.28990754e-01
     1.91036806e-01 -8

[[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
    0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0